[pytest]
testpaths = testes
python_files = teste_*.py
python_classes = Teste*
python_functions = testar_*
addopts = -ra --strict-markers --html=relatorios/relatorio.html --self-contained-html
markers =
    fumaça: verificacoes basicas de inicializacao da automacao
